addons:
  postgresql: "9.3"

language: go

before_script:
  - createuser -U postgres --createdb --superuser ohtu
  - createdb multi-axis-test -U postgres
  - psql multi-axis-test -U postgres < test.dump.sql

