addons:
  postgresql: "9.3"

language: java

jdk:
  - oraclejdk8

install:
  - gvm get
  - gvm update && source $HOME/.gvm/scripts/gvm
  - gvm install go1.3.3 --binary || gvm install go1.3.3
  - gvm use go1.3.3
  - go get -t -v ./...

before_script:
  - createuser -U postgres --createdb --superuser ohtu
  - psql -c 'create database multi_axis_test;' -U postgres
  - psql multi_axis_test -U postgres < test.dump.sql

script:
  - go test -v ./...
